- name: Get the secrets from HashiCorp Vault
  hosts: localhost
  tasks:
    - name: Read the latest version of a kv2 secrets
      community.hashi_vault.vault_kv2_get:
        url: https://vault.sirpi.in
        engine_mount_point: kv
        path: devops/heztner
        auth_method: token
        token: "{{ lookup('env', 'VAULT_TOKEN') }}"
      register: token_response

    - name: Display the results
      ansible.builtin.debug:
        msg:
          - "Secret: {{ token_response['secret']['r3.6.3-project-token'] }}"
          - "{{ token_response['secret']['r3.6.3-project-token'] }}"

    - name: Remove a firewall from a list of servers
      hetzner.hcloud.firewall_resource:
        api_token:  "{{ token_response['secret']['r3.6.3-project-token'] }}"
        firewall: workspace
        servers:
         - r3.6.3
        state: present
